## Расчетно-графическая работа 3. Таблица Кэли для шестиугольника

In [26]:
import pandas as pd

In [27]:
def get_elements(n):
    elements = []
    for i in range(n):
        if i == 0:
            elements.append("e")
        else:
            elements.append(f"a{i}")
    return elements

In [28]:
elements = get_elements(6)
cayley_table = pd.DataFrame(index=elements, columns=elements)
cayley_table

      e   a1   a2   a3   a4   a5
e   NaN  NaN  NaN  NaN  NaN  NaN
a1  NaN  NaN  NaN  NaN  NaN  NaN
a2  NaN  NaN  NaN  NaN  NaN  NaN
a3  NaN  NaN  NaN  NaN  NaN  NaN
a4  NaN  NaN  NaN  NaN  NaN  NaN
a5  NaN  NaN  NaN  NaN  NaN  NaN

In [29]:
def fill_table(df: pd.DataFrame):
    for i in range(len(df)):
        for j in range(len(df)):
            element_idx = (i + j) % len(df)
            if element_idx == 0:
                df.iloc[i, j] = "e"
            else:
                df.iloc[i, j] = f"a{element_idx}"
    return df

In [30]:
cayley_table = fill_table(cayley_table)
cayley_table

     e  a1  a2  a3  a4  a5
e    e  a1  a2  a3  a4  a5
a1  a1  a2  a3  a4  a5   e
a2  a2  a3  a4  a5   e  a1
a3  a3  a4  a5   e  a1  a2
a4  a4  a5   e  a1  a2  a3
a5  a5   e  a1  a2  a3  a4